---
- name: IP_assign
  hosts: "{{ cisco_asa }}"
  connection: network_cli
  #port: 22
  gather_facts: no

  tasks:
    - name: hostname config
      ios_system:
        hostname: "{{ inventory_hostname }}"
        lookup_enabled: 'no'

    - name: rtr-1 interface config
      ios_config:
        lines:
          - description connection asa-1 inside
          - ip address 10.0.255.254 255.255.255.0
          - ip address 10.0.255.10 255.255.255.0 secondary
          - ip address 10.0.255.11 255.255.255.0 secondary
          - ip address 10.0.255.12 255.255.255.0 secondary
        parents: Interface GigabitEthernet0/3
        after: no shutdown
