---
- name: IP_assign
  hosts: "{{ cisco_asa }}"
  connection: network_cli
  #port: 22
  gather_facts: no

  tasks:
    - name: configure network object-group
      asa_og:
        name: ansible_test_0
        group_type: network-object
        state: present
        description: ansible_test object-group description
        host_ip:
          - 8.8.8.8
          - 8.8.4.4
        ip_mask:
          - 10.0.0.0 255.255.255.0
          - 192.168.0.0 255.255.0.0
        group_object:
          - awx_lon
          - awx_ams
