---
- name: Show Version
  hosts: "{{ cisco_asa }}"
  connection: network_cli
  #port: 22
  gather_facts: no
  
- cisco.asa.asa_config:
    lines:
    - network-object host 10.80.30.18
    - network-object host 10.80.30.19
    - network-object host 10.80.30.20
    parents: [object-group network OG-MONITORED-SERVERS]
