---
- name: Show Running Config 
  hosts: "{{ cisco_router }}"
  connection: network_cli
  #port: 22
  gather_facts: no

  tasks:
    - name: IP Address
      ios_config:
        authorize: yes
        src: "config.txt"

