---
### Playbook to configure IOS Device

- name: Configuring IOS Devices
  hosts: phl_ios_devices
  gather_facts: no
  
  tasks:
    - name: Configure a single command
      ios_config: 
        lines: "{{ adhoc_config }}"
   
#
- name: Configuring CSR Devices
  hosts: phl_csr_devices
  gather_facts: no

  tasks:
    - name: Configure a single command
      ios_config: 
        lines: "{{ adhoc_config }}"

...
