---
   ### Playbook to backup the router Config

- name: Running task on local machine
  hosts: localhost # Running task on local machine
  gather_facts: no
  
  tasks:
    - name: Get Ansible date/time facts
      setup: 
        # ansible localhost -m setup -a "filter=ansible_date_time"
        filter: "ansible_date_time"
        gather_subset: "!all"
    
    - name: Store DTG information as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}" # .hour or .minute or .time
        #DTG: "{{ ansible_date_time.iso8601 }}"
        #DTG: "{{ ansible_date_time.weekday }}"
    
    - name: Create Directory using fact {{hostvars.localhost.DTG}}
      file:
        path: ~/afne/output/backup/{{ hostvars.localhost.DTG }}
        state: directory
  run_once: true


- name: Save Configuration for IOS Devices
  hosts: phl_ios_devices   # In AWX this is a group within Cisco Devices
  gather_facts: no
  
  tasks:  
    - name: Backup Running Config
      ios_command:
        commands: show run
      register: config

    - name: Save output to ~/afne/output/backup/{{hostvars.localhost.DTG}}
      copy:
        content: "{{config.stdout[0]}}"
        #dest: "~/afne/output/backup/{{hostvars.localhost.DTG}}/{{inventory_hostname}}-{{hostvars.localhost.DTG}}.txt"
        dest: "~/afne/output/backup/{{hostvars.localhost.DTG}}/{{inventory_hostname}}.txt"
        #dest: "~/afne/output/backup/{{inventory_hostname}}.txt"


- name: Save Configuration for CSR Devices
  hosts: phl_csr_devices       # In AWX this is a group within Cisco Devices
  gather_facts: no
  
  tasks:
    - name: Backup Running Config
      ios_command:
        commands: sh run
      register: config
    
    - name: Save output to ~/afne/output/backup/{{hostvars.localhost.DTG}}
      copy:
        content: "{{config.stdout[0]}}"
        #dest: "~/afne/output/backup/{{hostvars.localhost.DTG}}/{{inventory_hostname}}-{{hostvars.localhost.DTG}}.txt"
        dest: "~/afne/output/backup/{{hostvars.localhost.DTG}}/{{inventory_hostname}}.txt"
        #dest: "~/afne/output/backup/{{inventory_hostname}}.txt"


- name: Playbook to copy files from docker container to GitHub Directory 
  hosts: linux_centos
  tasks:

    - name: Copy file from docker to GitHub Directory
      command: docker cp 7d050b370f8f:/var/lib/awx/afne/output/backup /home/poku/github/ansible_tower_cisco
      become: yes
      become_method: sudo
    
    - name: List files in GitHub/ansible_cisco_tower dir
      command: ls -al /home/poku/github/ansible_tower_cisco/backup
      register: list_files
                  
    - name: Print -> "List of files and dir"
      debug: 
        var: list_files.stdout_lines
        
    - name: Checkout a github repo and use refspec to fetch all pull requests
      ansible.builtin.git:
        repo: https://github.com/poku-networker/ansible_tower_cisco.git
        dest: /home/poku/github/ansible_tower_cisco
        refspec: '+refs/pull/*:refs/heads/*'
...
