---
### Playbook to configure IOS Device

- name: Configuring IOS Devices
  hosts: phl_ios_devices
  gather_facts: no

  tasks:
    - name: Configure a single command
      ios_config: 
        lines: no ntp server 9.9.9.9
    
    - name: Configure multiple lines of code from text file
      ios_config:
        src: "~/afne/configuration/ntp.txt"
    
    - name: Save the config
      ios_config:
        save_when: always

- name: Configuring CSR Devices
  hosts: phl_csr_devices
  gather_facts: no

  tasks:
    - name: Configure a single command
      ios_config: 
        lines: no ntp server 9.9.9.9
    
    - name: Configure multiple lines of code from text file
      ios_config:
        src: "~/afne/configuration/ntp.txt"
    
    - name: Save the config
      ios_config:
        save_when: always
