---
## Playbook to show version on IOS

- name: Collect Diagnostic Output
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Run Two Diagnostic Commands
      ios_command:
        commands: 
          - show ip interface brief
          - show version
      register: output
    
    #- name: Run Multiple Diagnostic Commands
    #  ios_command: 
    #    src: "~/afne/configuration/diagnostic_commands.txt"
    #  register: mul_output
       
    
  
  #  - name: Print out the output
  #    debug: 
  #      var: output.stdout_lines
    
    - name: Save output to ~/afne/
      copy:
        content: "{{output.stdout[0] + output.stdout[1] }}"
        dest: "~/afne/output/diag/{{inventory_hostname}}.txt"
        
   # - name: Save output to ~/afne/ for multiple Commands
   #  copy:
   #    content: "{{mul_output.stdout[0] + mul_output.stdout[1] }}"
   #    dest: "~/afne/output/diag/{{inventory_hostname}}.txt"
