---
### Playbook to configure IOS Device

- name: Configuring IOS Devices
  hosts: phl_ios_mgmt1
  gather_facts: no
  
  tasks:
   
    - name: Configure MOTD Banner from File
      cisco.ios.ios_banner:
        banner: motd
        text: "{{ lookup('file', 'roles/awx_eveng_lab/configs/motd_banner.j2') }}"
        state: present
        
    - name: Save the config
      ios_config:
        save_when: always
