---
### Playbook to configure IOS Device

- name: Configuring IOS Devices
  hosts: phl_ios_mgmt1
  gather_facts: no
  
  tasks:
   
    - name: Configure MOTD Banner from Jinja2 Template
      include_role:
        name: awx_eveng_lab
        tasks_from: motd_banner.yml
        vars_from: global_vars
    
    - name: Save the config
      ios_config:
        save_when: always
