---
### Playbook to configure Vlan on IOS Device

- name: Playbook to use Diagnostic Output as information source for next task
  hosts: phl-ios-sw1
  gather_facts: no


  tasks:
    - name: Find STP root and blocked Ports
      ios_command:
        commands: show spanning-tree vlan 450 root
      register: stp_output
    
    - set_fact:
        #root_port: "{{ stp_output.stdout_lines[0][3].split()[7] | regex_replace('"', '') }}"
        root_port: "{{ stp_output.stdout[0][3].split() }}"
    
    - name: Print out the output
      debug: 
        var: root_port

    - name: Print out the output
      debug: 
        var: stp_output.stdout_lines
    
    - name: Sh Running Configuration of Root Port
      ios_command:
        commands: show run interface "{{ root_port | int }}"
      register: int_output
    
    - name: Print out the output
      debug: 
        var: int_output.stdout_lines

...
