---
# Playbook to copy files from docker container to GitHub Directory 

- hosts: linux_centos
  tasks:

    - name: Copy file from docker to GitHub Directory
      command: docker cp 7d050b370f8f:/var/lib/awx/afne/output/backup /home/poku/github/ansible_tower_cisco
      become: yes
      become_method: sudo
    
    - name: List files in GitHub/ansible_cisco_tower dir
      command: ls -al /home/poku/github/ansible_tower_cisco/backup
      register: list_files
                  
    - name: Print -> "List of files and dir"
      debug: 
        msg: "{{ list_files.stdout }}"
        #msg: "{{ list_files.stdout_lines[0]+list_files.stdout_lines[1]+list_files.stdout_lines[2]\n+list_files.stdout_lines[3]\n+list_files.stdout_lines[4]\n }}"
