---
- name: show ip info & ARP
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: run multiple commands on remote nodes
      ios_command:
        authorize: yes
        commands:
          - show ip int br
          - show arp

