---
- name: Playbook to Build Network Device Configuration
  hosts: linux_centos # This will cause the file to be stored native to centos linux instead of docker container
  gather_facts: no
  
  tasks:
    - name: Start Building Device Configuration
      include_role:
        name: awx_eveng_lab
        tasks_from: build_device_configuration.yml
        vars_from: build_device_configuration.yml
