---
## Playbook to save configuration on IOS

- name: Copy Running Config to Start-up Config
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Save the config
      ios_config:
        save_when: always
