---
- name: Show interface information
  hosts: all
  connection: network_cli
  #port: 22
  gather_facts: no

  tasks:
    - name: Command sh ip int br
      ios_command:
        authorize: yes
        commands:
          - show ip int br
      register: output

    - name: Print out the output
      debug: 
        var: output.stdout_lines
