
---
- name: Assign IP addreaa
  hosts: "{{ cisco_asa }}"
  connection: network_cli
  #port: 22
  gather_facts: no

  tasks:
    - name: Configuration IP G0/3
      asa_config:
        parents: Interface GigabitEthernet0/3
        lines:
          - description connection asa-1 inside
          - ip address 172.16.1.10 255.255.255.0
          - no shutdown
