1 - ARP playbook.yml
---
- name: Get ARP information
  hosts: all
  gather_facts: false


  tasks:
    - name: show arp
      raw: "show arp"

      register: print_output

    -  debug: var=print_output.stdout_lines


# Commands to run: 
#1) ansible-playbook test.yml -u sultan -k
#2) Grep for MAC address: ansible-playbook test.yml -u sultan -k | grep ok:\|fe7a'
#3) Grep for IP address: ansible-playbook test.yml -u sultan -k | grep ok:\|122\.3'




2 - MAC address table playbook.yml
---
- name: Get MAC address table information
  hosts: all
  gather_facts: false


  tasks:
    - name: show MAC address table
      raw: "show mac address-table"

      register: print_output

    -  debug: var=print_output.stdout_lines


# Commands to run: 
#1) ansible-playbook getmac1.yml -u sultan -k
#2) Grep for MAC address: ansible-playbook getmac1.yml -u sultan -k | grep 'ok:\|29bd'





3 - sh version - user mode Part 1.yml
---
- name: show version and other user level commands
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show version
          - show ip int brief


      register: print_output

    -  debug: var=print_output.stdout_lines


# Description:
# Use the ios commands module to get show version information and show interfaces information. 
# These are user mode commands.
# http://docs.ansible.com/ansible/latest/ios_command_module.html

# Commands to run: 
#1) ansible-playbook shver1.yml -u sultan -k





4 - sh version - user mode Part 2.yml
---
- name: Backup show version and other user level commands
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show version

      register: print_output

    -  debug: var=print_output.stdout_lines

    - name: save output to a file
      copy: content="{{ print_output.stdout[0] }}" dest="./output/{{ inventory_hostname }}.txt"


# Description:
# Use the ios commands module to get show version information and show interfaces information. 
# These are user mode commands.
# Save the output to files
# http://docs.ansible.com/ansible/latest/ios_command_module.html

# Commands to run: 
#1) ansible-playbook shver2.yml -u sultan -k




5 - sh run - exec mode Part 3.yml
---
- name: Backup show run (enable mode commands)
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: run enable level commands
      ios_command:
        authorize: yes
        commands:
          - show run

      register: print_output

    -  debug: var=print_output.stdout_lines

    - name: save output to a file
      copy: content="{{ print_output.stdout[0] }}" dest="./output/{{ inventory_hostname }}.txt"


# Description:
# Use the ios commands module to get show run information 
# Go to enable mode
# Save the output to files
# http://docs.ansible.com/ansible/latest/ios_command_module.html

# Commands to run: 
#1) ansible-playbook shver3.yml -u sultan -k

